const ERROR_CODES = {
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_REQUIRED: 'AUTH_REFRESH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INVALID_CSRF_TOKEN: 'INVALID_CSRF_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  NOT_FOUND: 'NOT_FOUND',
  SYSTEM_BOOTSTRAP_MISSING: 'SYSTEM_BOOTSTRAP_MISSING',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_SUSPENDED: 'USER_SUSPENDED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

module.exports = {
  ERROR_CODES,
};
